version: '1.0'
services:
  front-hackathon:
    build: ./client
    container_name: front-hackathon
    ports: 
    - '5173:5173'
    restart: always
    depends_on:
      - back-hackathon
      - db-hackathon
    networks:
      - opennet

  back-hackathon:
    build: ./Back-end
    container_name: back-hackathon
    ports: 
    - '8080:8080'
    restart: always
    depends_on:
      - db-hackathon
    networks:
      - opennet

  db-hackathon:
    image: postgres
    ports:
      - '5436:5432'
    container_name: db-hackathon
    restart: always
    environment:
      - "POSTGRES_PASSWORD=123321"
    networks:
      - opennet

networks:
  opennet: